# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-DYoSWGCm9iCS4b5w9kB-TdtPj-kcGjj
"""

import pandas as pd
import joblib

# Step 1: Load the pre-trained model from the .pkl file
gb_adasyn_model = joblib.load('adasyn_stacking_model.pkl')

# Step 2: Prepare the input data as a Pandas DataFrame
input_data = pd.DataFrame({
    'SourceIP': [1.465648769, 0.677925871],
    'DestinationIP': [-0.2257763, -0.487911408],
    'SourcePort': [0.067528205, 2.157308213],
    'DestinationPort': [-1.424748186, -0.605714923],
    'Protocol': [-0.544382725, 0.742095372],
    'BytesSent': [0.11092259, 0.29929258],
    'BytesReceived': [-1.150993577, 1.301741289],
    'PacketsSent': [0.375698018, 1.561511197],
    'PacketsReceived': [-0.60063869, 0.032004149],
    'Duration': [-0.29169375, -0.75341787]
})

# Step 3: Make predictions
predicted_output = gb_adasyn_model.predict(input_data)

# Display the predicted output
print("Predicted IsAnomaly:", predicted_output)

import pandas as pd
import joblib

# Step 1: Load the pre-trained model from the .pkl file
gb_adasyn_model = joblib.load('adasyn_random_forest_model.pkl')

# Step 2: Prepare the new input data as a Pandas DataFrame
new_input_data = pd.DataFrame({
    'SourceIP': [0.572006278, 0.633661025],
    'DestinationIP': [-0.704728436, -0.698199675],
    'SourcePort': [-1.537584796, 1.678674673],
    'DestinationPort': [-0.144904579, -1.911640551],
    'Protocol': [-0.445943714, 1.311167498],
    'BytesSent': [0.113140457, -0.224318971],
    'BytesReceived': [-0.363116661, 0.859584872],
    'PacketsSent': [-2.007456861, 0.079801484],
    'PacketsReceived': [-0.388346938, 1.139555536],
    'Duration': [-0.305619111, -0.387361965]
})

# Step 3: Make predictions
predicted_output = gb_adasyn_model.predict(new_input_data)

# Display the predicted output
print("Predicted IsAnomaly:", predicted_output)